/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as DnaRouteImport } from './routes/dna'
import { Route as FaultsRouteImport } from './routes/faults'
import { Route as HealthRouteImport } from './routes/health'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as ApiWorldRouteImport } from './routes/api/world'
import { Route as AssetIdRouteImport } from './routes/asset/$id'
import { Route as InvestigateAssetIdRouteImport } from './routes/investigate/$assetId'
import { Route as MethodologyIndexRouteImport } from './routes/methodology/index'
import { Route as MethodologyDataRouteImport } from './routes/methodology/data'
import { Route as SectorsIndexRouteImport } from './routes/sectors/index'
import { Route as SectorsSlugRouteImport } from './routes/sectors/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaRoute = DnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => rootRouteImport,
} as any)
const FaultsRoute = FaultsRouteImport.update({
  id: '/faults',
  path: '/faults',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorldRoute = ApiWorldRouteImport.update({
  id: '/api/world',
  path: '/api/world',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdRoute = AssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateAssetIdRoute = InvestigateAssetIdRouteImport.update({
  id: '/investigate/$assetId',
  path: '/investigate/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyIndexRoute = MethodologyIndexRouteImport.update({
  id: '/methodology/',
  path: '/methodology/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyDataRoute = MethodologyDataRouteImport.update({
  id: '/methodology/data',
  path: '/methodology/data',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsIndexRoute = SectorsIndexRouteImport.update({
  id: '/sectors/',
  path: '/sectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSlugRoute = SectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/changes': typeof ChangesRoute
  '/dna': typeof DnaRoute
  '/faults': typeof FaultsRoute
  '/health': typeof HealthRoute
  '/search': typeof SearchRoute
  '/signals': typeof SignalsRoute
  '/api/world': typeof ApiWorldRoute
  '/asset/$id': typeof AssetIdRoute
  '/investigate/$assetId': typeof InvestigateAssetIdRoute
  '/methodology/data': typeof MethodologyDataRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/methodology/': typeof MethodologyIndexRoute
  '/sectors/': typeof SectorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/changes': typeof ChangesRoute
  '/dna': typeof DnaRoute
  '/faults': typeof FaultsRoute
  '/health': typeof HealthRoute
  '/search': typeof SearchRoute
  '/signals': typeof SignalsRoute
  '/api/world': typeof ApiWorldRoute
  '/asset/$id': typeof AssetIdRoute
  '/investigate/$assetId': typeof InvestigateAssetIdRoute
  '/methodology/data': typeof MethodologyDataRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/methodology': typeof MethodologyIndexRoute
  '/sectors': typeof SectorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/changes': typeof ChangesRoute
  '/dna': typeof DnaRoute
  '/faults': typeof FaultsRoute
  '/health': typeof HealthRoute
  '/search': typeof SearchRoute
  '/signals': typeof SignalsRoute
  '/api/world': typeof ApiWorldRoute
  '/asset/$id': typeof AssetIdRoute
  '/investigate/$assetId': typeof InvestigateAssetIdRoute
  '/methodology/data': typeof MethodologyDataRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/methodology/': typeof MethodologyIndexRoute
  '/sectors/': typeof SectorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/changes'
    | '/dna'
    | '/faults'
    | '/health'
    | '/search'
    | '/signals'
    | '/api/world'
    | '/asset/$id'
    | '/investigate/$assetId'
    | '/methodology/data'
    | '/sectors/$slug'
    | '/methodology/'
    | '/sectors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/changes'
    | '/dna'
    | '/faults'
    | '/health'
    | '/search'
    | '/signals'
    | '/api/world'
    | '/asset/$id'
    | '/investigate/$assetId'
    | '/methodology/data'
    | '/sectors/$slug'
    | '/methodology'
    | '/sectors'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/changes'
    | '/dna'
    | '/faults'
    | '/health'
    | '/search'
    | '/signals'
    | '/api/world'
    | '/asset/$id'
    | '/investigate/$assetId'
    | '/methodology/data'
    | '/sectors/$slug'
    | '/methodology/'
    | '/sectors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ChangesRoute: typeof ChangesRoute
  DnaRoute: typeof DnaRoute
  FaultsRoute: typeof FaultsRoute
  HealthRoute: typeof HealthRoute
  SearchRoute: typeof SearchRoute
  SignalsRoute: typeof SignalsRoute
  ApiWorldRoute: typeof ApiWorldRoute
  AssetIdRoute: typeof AssetIdRoute
  InvestigateAssetIdRoute: typeof InvestigateAssetIdRoute
  MethodologyDataRoute: typeof MethodologyDataRoute
  SectorsSlugRoute: typeof SectorsSlugRoute
  MethodologyIndexRoute: typeof MethodologyIndexRoute
  SectorsIndexRoute: typeof SectorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna': {
      id: '/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof DnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faults': {
      id: '/faults'
      path: '/faults'
      fullPath: '/faults'
      preLoaderRoute: typeof FaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/world': {
      id: '/api/world'
      path: '/api/world'
      fullPath: '/api/world'
      preLoaderRoute: typeof ApiWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$id': {
      id: '/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate/$assetId': {
      id: '/investigate/$assetId'
      path: '/investigate/$assetId'
      fullPath: '/investigate/$assetId'
      preLoaderRoute: typeof InvestigateAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology/': {
      id: '/methodology/'
      path: '/methodology'
      fullPath: '/methodology/'
      preLoaderRoute: typeof MethodologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology/data': {
      id: '/methodology/data'
      path: '/methodology/data'
      fullPath: '/methodology/data'
      preLoaderRoute: typeof MethodologyDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/': {
      id: '/sectors/'
      path: '/sectors'
      fullPath: '/sectors/'
      preLoaderRoute: typeof SectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$slug': {
      id: '/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof SectorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ChangesRoute: ChangesRoute,
  DnaRoute: DnaRoute,
  FaultsRoute: FaultsRoute,
  HealthRoute: HealthRoute,
  SearchRoute: SearchRoute,
  SignalsRoute: SignalsRoute,
  ApiWorldRoute: ApiWorldRoute,
  AssetIdRoute: AssetIdRoute,
  InvestigateAssetIdRoute: InvestigateAssetIdRoute,
  MethodologyDataRoute: MethodologyDataRoute,
  SectorsSlugRoute: SectorsSlugRoute,
  MethodologyIndexRoute: MethodologyIndexRoute,
  SectorsIndexRoute: SectorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
